### ISSUE TITLE
Markdown language and usage in Gitlab

### ISSUE THREAD

**Issue by Nicewithothers** [ChironSZTE/cave-of-chiron#12]
# Markdown language

## Introduction
Why Markdown? I think it's a good question. It is a very lightweighted and useful formatting language, founded in 2004 by **John Gruber** that is used to format text with smart syntax, very good for documentation, such as testing, readmes and etc.

**IMPORTANT NOTE: Actually, GitHub and GitLab are very similar in terms of what kind of `.md` language they're using, so I'm incorporating them into one big comment.**

***In the following paragraphs we're going through some of the most essential that this language can offer to us. I'll include some extras and examples too but the main focus is on the basics.***
<br>
Let's not waste time, shall we?
## Headings
To create a heading, you need to put a `#` before your text, following a whitespace character. The number of `#` will define your heading's size.
```
# This is the same as <h1> in HTML
## This is the same as <h2> in HTML
### This is the same as <h3> in HTML
```
etc.

## Styling text
There are a number of ways to format your text, such as bold, italic, strikethrough, subscript and superscript.

- Bold -> `** **` or `__ __` -> **This is an example bold text**
- Italic -> `* *` or `_ _` -> *This is an example italic text*
- Strikethrough -> `~~ ~~` -> ~~This is an example strikethrough text~~
- Bold and italic -> `*** ***` -> ***This is an example bold and italic text***
- Subscript -> `<sub></sub>` -> This is an example<sub>formula</sub> text
- Superscript -> `<sup></sup>` -> This is an example<sup>formula</sup> text

## Quoting text
You can also quote a text, that means it gets a gray line at the end of the container plus a gray font color.
> This is an example quote text

There is also a very great use of quoting inside texts with backticks.
This is a very good example text `with code` at the end.

And also we can create code blocks with three backticks before and after a code snippet. If it's a code we can add the language after the first three backticks, and it'll color the keywords. There'll be two examples of codes below this text.

```
public class Main {
    public static void main(String[] args) {
        System.out.println("Hello world!");
    }
}
```
<hr>

```java
public class Main {
    public static void main(String[] args) {
        System.out.println("Hello world!");
    }
}
```

As we can see, the second example is much more user-friendly than the first one. It is highly recommended to use.

## Links
We can create links with custom names. The custom name goes inside of brackets `[]` and the link goes immediatly after the bracket in parentheses `()`.

`This is an example link for GitLab: [Gitlab](https://about.gitlab.com/)`
[GitLab](https://about.gitlab.com/)

If you need to, you can use **relative links** too, with the `/`, `./` and `../`. It is not necessary but recommended especially if you're working with local files.

## Images
You can also insert images inside a comment by using almost the same as in the Links section, except you need to "mark" your syntax with an exclamation mark or `!`.

`![This is an example image of GitLab](https://gitlab.com/uploads/-/system/group/avatar/6543/logo-extra-whitespace.png)`
![This is an example image of GitLab](https://gitlab.com/uploads/-/system/group/avatar/6543/logo-extra-whitespace.png)

## Lists

You can make unordered lists with `-`, `*`, or `+`. If you want to make an ordered list, use numbers and precede them.

- This
+ Is
* An
+ Unordered
- List
<hr>

1. This
2. Is
3. An
4. Ordered
5. List

You can also nest lists in each other.

1. First item
	- Second item
		- Third item

## Task lists
You can do checkboxes for tracking tasks, by using `-`, whitespace and `[ ]` with a whitespace between them. If you want to check them, you need to replace the whitespace inside of the brackets for an `X`, like this: `[X]`.

- [ ] #1111
- [ ] First task
- [X] Second task

## Mentioning
There are two types of mentioning:
1. People and teams -> With `@<person/team>` -> @Nicewithothers 
2. Issues and pull requests -> With `#<issue/pr_number>` -> #12

## Comments
You can comment with this syntax: `<!-- This is an example comment text -->`

## Final thoughts
I want to add that you can use HTML tags like I used in this comment a lot. I also want to point out that this is only the basic knowledge of MarkDown language, but it is well enough for documenting already.

**Comment by ChimiChumi** [comment]
Thanks for helping in setting up the CodeMetropolis project.

**Comment by gyarmati21** [comment]
Helped me a ton during my project work!
